### ISSUE TITLE
Spoken Sessions.

### ISSUE THREAD

**Issue by serge-nikitin** [letsdiscuss-tech/letsdiscuss.tech#76]
What do you think about "Spoken Sessions" term?

Can we replace Meetings -> Discussions -> Spoken Sessions? I want to use the word "spoken" to emphasize that it's not a forum/blog, that members speak about IT topics.

What about menu:

- Topics - 321
- Spoken Sessions - 12

Does it look OK?

And what about "Planned Spoken Sessions" and "Completed Spoken Sessions"?

**Comment by csmith111** [comment]
Hi Serge, 
I find that spoken sessions is too "literal" so it does not sound great. 
I still think that **Discussion** or **Session** are good because they emphasize the event and the exchange of information but do not stress the medium used, written, audio(spoken) or video etc. Which is think is nice.  
I think that Session is good since it emphasizes that is not a blog. Since you cannot have a Session on a blog. (Btw.. you don't speak on a blog.. you write on a blog.)
So I recommend **Planned Session** and **Completed Session** you could have a SessionType or SessionFormat which could be Chat, Video Call, VoiceCall, ScreenShare etc. Then there would be no confusion. 
I suggest writing a product description in a couple of lines... let us review that and see if we can do something to make sure the marketing/description does not make it sound like a forum/blog.
